### ISSUE TITLE
Disable interactive mode to support CI pipelines

### ISSUE THREAD

**Issue by yugoccp** [allanmaral/dotrepo#11]
Thanks for the project, awesome initiative! Please add option to disable interactive mode so I can use the CLI at my CI pipelines :)

**Comment by allanmaral** [comment]
Sure! 
Version 0.0.7 will include a global --ci option to disable text colors and the "version" command will include a --yes option to auto confirm the prompt.

**Comment by yugoccp** [comment]
> Sure! Version 0.0.7 will include a global --ci option to disable text colors and the "version" command will include a --yes option to auto confirm the prompt.

Wow! That was fast! Cheers! 😆
